// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Int Function(ffi.Pointer<ffi.Char>, ffi.Pointer<statvfs>)>(
  symbol: 'statvfs',
)
external int statvfs$1(
  ffi.Pointer<ffi.Char> __file,
  ffi.Pointer<statvfs> __buf,
);

@ffi.Native<ffi.Int Function(ffi.Int, ffi.Pointer<statvfs>)>()
external int fstatvfs(int __fildes, ffi.Pointer<statvfs> __buf);

final class statvfs extends ffi.Struct {
  @ffi.UnsignedLong()
  external int f_bsize;

  @ffi.UnsignedLong()
  external int f_frsize;

  @ffi.UnsignedLong()
  external int f_blocks;

  @ffi.UnsignedLong()
  external int f_bfree;

  @ffi.UnsignedLong()
  external int f_bavail;

  @ffi.UnsignedLong()
  external int f_files;

  @ffi.UnsignedLong()
  external int f_ffree;

  @ffi.UnsignedLong()
  external int f_favail;

  @ffi.UnsignedLong()
  external int f_fsid;

  @ffi.UnsignedLong()
  external int f_flag;

  @ffi.UnsignedLong()
  external int f_namemax;

  @ffi.UnsignedInt()
  external int f_type;

  @ffi.Array.multi([5])
  external ffi.Array<ffi.Int> __f_spare;
}
